#This code reads the data "Enrs.txt" generated by Brandhorst and Shimada in GAP format
#See 10.5281/zenodo.4327019
#It produces as output several files "N.txt", where N is the number of the $(\tau,\overline{\tau})$-generic Enriques surfaces in the list of Brandhorst and Shimada
#Such files contain, in JSON format, the list 'Ratstemp' and the list 'Autrec' 

import json

def convert(o):
    #A function to convert the type GapElement_Integer into the type Integer used in SageMath
    #This is done both for integers and for lists of integers
    
    if (isinstance(o, sage.libs.gap.element.GapElement_Integer)): return int(o)
    if (isinstance(o, sage.libs.gap.element.GapElement_List)): 
        if (isinstance(o[0], sage.libs.gap.element.GapElement_Integer)): return [int(x) for x in o]
        if (isinstance(o[0], sage.libs.gap.element.GapElement_List)): return [[int(y) for y in x] for x in o]
    raise TypeError

#Read the file "Enrs.txt". Since the file is quite big, to speed up the code we suggest to split the whole "Enrs.txt" into several files
libgap.Read("Enrs.txt")

Enrs=libgap.Enrs
LengthListEnrs=len(Enrs)
print("Importing ",LengthListEnrs," Enriques")
for i in range(LengthListEnrs):
    NumberInTheList=Enrs[i]['no']
    print("\tImporting the ",i,"-th element, corresponding to number",NumberInTheList, "in the list.")
    ListRatsTemp=[]
    
    RatsListForThisEnriques=Enrs[i]['Rats']['Ratstemp']
    LengthRatsListForThisEnriques=len(RatsListForThisEnriques)
    for j in range(LengthRatsListForThisEnriques):
        ListRatsTemp.append(RatsListForThisEnriques[j]['rat']['ratY'])
        
    ListAutRec=[]
    AutrecListForThisEnriques=Enrs[i]['Autrec']['HHH']
    LengthAutrecListForThisEnriques=len(AutrecListForThisEnriques)
    for j in range(LengthAutrecListForThisEnriques):
        ListAutRec.append(AutrecListForThisEnriques[j]['gY'])
        
    NewEnriques={'no':NumberInTheList,
                 'Ratstemp':ListRatsTemp,
                 'Autrec':ListAutRec
                }
                
    with open(str(NumberInTheList)+'.txt', 'w') as fp:
        json.dump(NewEnriques, fp, default=convert)
    